version: 2
jobs:
  build:
    working_directory: /srv
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm install
      - run: node_modules/.bin/eslint --format junit -o /tmp/junit/eslint.xml
      - run: node_modules/.bin/jest --ci --testResultsProcessor="jest-junit"