version: 2
jobs:
  test:
    working_directory: /srv
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm install
      - run:
          name: "ESLint"
          command: node_modules/.bin/eslint --format junit -o /tmp/junit/eslint.xml
      - run:
          name: "Jest"
          command: node_modules/.bin/jest --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "/tmp/junit/jest.xml"
      - run: npm run build
      - store_test_results:
          path: /tmp/junit
      - persist_to_workspace:
          root: /srv
          paths:
            - dist

  publish:
    working_directory: /srv
    docker:
      - image: node:8
    steps:
      - checkout
      - attach_workspace:
          at: /srv
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: echo $CIRCLE_TAG
#      - run: npm publish --tag $CIRCLE_TAG

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - publish:
          requires: [test]
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
